# permissions for end users to edit emails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailerlite
    app.kubernetes.io/managed-by: kustomize
  name: email-editor-role
rules:
- apiGroups:
  - k8s.magusd.com.my.domain
  resources:
  - emails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.magusd.com.my.domain
  resources:
  - emails/status
  verbs:
  - get
