apiVersion: k8s.magusd.com.my.domain/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: mailerlite
    app.kubernetes.io/managed-by: kustomize
  name: email-sample
spec:
  senderConfigRef: mailgun
  recipientEmail: vitor.lobs@gmail.com
  subject: hello
  body: world mailgun!
---
apiVersion: k8s.magusd.com.my.domain/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: mailerlite
    app.kubernetes.io/managed-by: kustomize
  name: email-sample-mailsend
spec:
  senderConfigRef: mailsend
  recipientEmail: vitor.lobs@gmail.com
  subject: hello mailsend
  body: world mailsend!
