apiVersion: k8s.magusd.com.my.domain/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: mailerlite
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
