apiVersion: v1
kind: Secret
metadata:
  name: mailgun-token
data:
  provider:  bWFpbGd1bg==
  domain: bG9ic3dlYi5tYWlsZ3VuLm9yZw==
  token: OWQyZWJiNWNhYTI5NjQ4MWRhNThmOGU4N2Q5MGU1ZWQtMDk5NjQwOWItODM3YmZhOTI=

---
apiVersion: v1
kind: Secret
metadata:
  name: mailsend-token
data:
  provider: bWFpbHNlbmQ=
  domain: dHJpYWwtank3enBsOXhxanJsNXZ4Ni5tbHNlbmRlci5uZXQ=
  token: bWxzbi41YmFlMDMxMzE5Y2FjZTBmOGIwZDhjMjIxYmZhM2NjMWU1NjQ1ODYyZWI2MGZkODg1ZDBiMDdhZDE1YWUwYjg2
